[pytest]
# Parametro para definir archivos a ejecutar (En este caso todos los que inicien con "test_")
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# addopts agrega opciones automáticamente a cada ejecución
# en este caso todas las ejecuciones van a ser en modo verbose y generarán reporte
addopts = -v --html=reports/reporte.html --self-contained-html

markers =
    api: tests de API
    ui: tests de UI