name:
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: '3.14'
      PIP_CACHE: ~/.cache/pip

    steps:
      - name: Checkout código
        uses: actions/cache@v4
        with:
          path ${{ env.PIP_CACHE }}
                            